# [1] Scientific computation

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Some-arithmetic-insights" data-toc-modified-id="Some-arithmetic-insights-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Some arithmetic insights</a></span><ul class="toc-item"><li><span><a href="#Integers" data-toc-modified-id="Integers-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span><a href="https://docs.python.org/3/c-api/long.html" target="_blank">Integers</a></a></span></li><li><span><a href="#Floats" data-toc-modified-id="Floats-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span><a href="https://docs.python.org/3/tutorial/floatingpoint.html" target="_blank">Floats</a></a></span></li></ul></li><li><span><a href="#SciPy.org's-Numpy" data-toc-modified-id="SciPy.org's-Numpy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>SciPy.org's <a href="http://www.numpy.org/" target="_blank">Numpy</a></a></span><ul class="toc-item"><li><span><a href="#Installation" data-toc-modified-id="Installation-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Installation</a></span></li><li><span><a href="#Why-numpy?" data-toc-modified-id="Why-numpy?-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Why numpy?</a></span></li><li><span><a href="#Creating-(simple)-arrays-in-Numpy" data-toc-modified-id="Creating-(simple)-arrays-in-Numpy-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Creating (simple) <a href="https://docs.scipy.org/doc/numpy-dev/user/quickstart.html" target="_blank">arrays</a> in Numpy</a></span></li><li><span><a href="#1D-arrays" data-toc-modified-id="1D-arrays-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>1D arrays</a></span></li><li><span><a href="#1.3.3.-2D-arrays" data-toc-modified-id="1.3.3.-2D-arrays-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>1.3.3. 2D arrays</a></span></li><li><span><a href="#1.3.4.-N-dimensional-array" data-toc-modified-id="1.3.4.-N-dimensional-array-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>1.3.4. N-dimensional array</a></span></li><li><span><a href="#1.4.-Slicing" data-toc-modified-id="1.4.-Slicing-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>1.4. Slicing</a></span></li><li><span><a href="#1.5.-Boolean-array-indexing" data-toc-modified-id="1.5.-Boolean-array-indexing-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>1.5. Boolean array indexing</a></span></li><li><span><a href="#1.6.-Elementwise-(vectorial-vectorial-and-vectorial-scalar)-math" data-toc-modified-id="1.6.-Elementwise-(vectorial-vectorial-and-vectorial-scalar)-math-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>1.6. Elementwise (vectorial-vectorial and vectorial-scalar) math</a></span></li><li><span><a href="#1.7.-Broadcasting" data-toc-modified-id="1.7.-Broadcasting-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>1.7. Broadcasting</a></span></li><li><span><a href="#1.8.-Matricial-math" data-toc-modified-id="1.8.-Matricial-math-2.11"><span class="toc-item-num">2.11&nbsp;&nbsp;</span>1.8. Matricial math</a></span></li><li><span><a href="#1.9.-How-fast-is-Numpy's-array-math?" data-toc-modified-id="1.9.-How-fast-is-Numpy's-array-math?-2.12"><span class="toc-item-num">2.12&nbsp;&nbsp;</span>1.9. How fast is Numpy's array math?</a></span></li><li><span><a href="#1.10.-Structured-arrays" data-toc-modified-id="1.10.-Structured-arrays-2.13"><span class="toc-item-num">2.13&nbsp;&nbsp;</span>1.10. Structured arrays</a></span></li><li><span><a href="#Output-data-to-an-ASCII-file" data-toc-modified-id="Output-data-to-an-ASCII-file-2.14"><span class="toc-item-num">2.14&nbsp;&nbsp;</span>Output data to an ASCII file</a></span></li></ul></li><li><span><a href="#2.-Matplotlib" data-toc-modified-id="2.-Matplotlib-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>2. <a href="http://matplotlib.org" target="_blank">Matplotlib</a></a></span><ul class="toc-item"><li><span><a href="#2.1.-Installation" data-toc-modified-id="2.1.-Installation-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>2.1. Installation</a></span></li><li><span><a href="#2.2.-Configure-Matplotlib-in-line-of-IPython-(~Jupyter)-notebook" data-toc-modified-id="2.2.-Configure-Matplotlib-in-line-of-IPython-(~Jupyter)-notebook-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>2.2. Configure Matplotlib in-line of IPython (~Jupyter) notebook</a></span></li><li><span><a href="#2.3.-Importing-it" data-toc-modified-id="2.3.-Importing-it-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>2.3. Importing it</a></span></li><li><span><a href="#2.4.-Drawing-data-structures-(matrices):" data-toc-modified-id="2.4.-Drawing-data-structures-(matrices):-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>2.4. Drawing data structures (matrices):</a></span></li><li><span><a href="#2.5.-Drawing-2D-curves" data-toc-modified-id="2.5.-Drawing-2D-curves-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>2.5. Drawing 2D curves</a></span></li><li><span><a href="#2.6.-Drawing-3D-curves" data-toc-modified-id="2.6.-Drawing-3D-curves-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>2.6. Drawing 3D curves</a></span></li></ul></li><li><span><a href="#3.-SciPy" data-toc-modified-id="3.-SciPy-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>3. <a href="https://docs.scipy.org/doc/scipy/reference/" target="_blank">SciPy</a></a></span><ul class="toc-item"><li><span><a href="#3.1.-Installation" data-toc-modified-id="3.1.-Installation-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>3.1. Installation</a></span></li><li><span><a href="#3.1.1.-Optimization-example" data-toc-modified-id="3.1.1.-Optimization-example-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>3.1.1. Optimization example</a></span></li></ul></li><li><span><a href="#4.-Pandas" data-toc-modified-id="4.-Pandas-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>4. <a href="http://pandas.pydata.org/" target="_blank">Pandas</a></a></span><ul class="toc-item"><li><span><a href="#4.1.-Installation" data-toc-modified-id="4.1.-Installation-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>4.1. Installation</a></span></li><li><span><a href="#4.2.-Example" data-toc-modified-id="4.2.-Example-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>4.2. Example</a></span></li></ul></li><li><span><a href="#5.-SymPy" data-toc-modified-id="5.-SymPy-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>5. <a href="http://www.sympy.org/en/index.html" target="_blank">SymPy</a></a></span><ul class="toc-item"><li><span><a href="#5.1.-Install" data-toc-modified-id="5.1.-Install-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>5.1. Install</a></span></li><li><span><a href="#5.2.-Example" data-toc-modified-id="5.2.-Example-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>5.2. Example</a></span></li></ul></li></ul></div>

There are several packages that provide multidimensional data manipulation, optimization, regression, interpolation and visualization, among other possibilities.

## Some arithmetic insights

### [Integers](https://docs.python.org/3/c-api/long.html)

In python, integers have arbitrary precision and therefore we can represent an arbitrarily large range of integers (only limited by the available memory).

In [1]:
x = 7**273
print(x)
print(type(x))

514949835672429280118340184962210764526557059561644551308225135656646772567852802341125202657808555553768425192667497268234055382589043229395747814284702360571674673819941501856557513477604134701802987908639670470095067188938102407
<class 'int'>


### [Floats](https://docs.python.org/3/tutorial/floatingpoint.html)

Python uses (hardware) [754 double precision representation](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64) for floats. This means that some floats can be only represented approximately.

* Using [string format](https://docs.python.org/3.4/library/string.html#string-formatting) to see the precision limitation of **doubles** in Python. For example, it is impossible to represent exactly the number `0.1`:

In [2]:
format(0.1, '.80f')

'0.10000000000000000555111512312578270211815834045410156250000000000000000000000000'

* This can give us *surprises*:

In [3]:
.1 + .1 + .1 == .3

False

In [4]:
.1  + .1 == .2

True

* For "infinite" precision float arithmetic you can use [decimal](https://docs.python.org/3/library/decimal.html#module-decimal) or [mpmath](http://mpmath.org):

In [5]:
from decimal import Decimal, getcontext

* Getting 30 digits of 1/7:

In [6]:
getcontext().prec=80
format(Decimal(1)/Decimal(7), '.80f')

'0.14285714285714285714285714285714285714285714285714285714285714285714285714285714'

* We can see how many digits are true of 1/7 using doubles:

In [7]:
format(1/7, '.80f')

'0.14285714285714284921269268124888185411691665649414062500000000000000000000000000'

In [8]:
#12345678901234567 (17 digits)

* Decimal arithmetic produces decimal objects:

In [9]:
Decimal(1)/Decimal(7)

Decimal('0.14285714285714285714285714285714285714285714285714285714285714285714285714285714')

* Decimal objects can be printed with `format`:

In [10]:
print('{:.50f}'.format(Decimal(1)/Decimal(7)))

0.14285714285714285714285714285714285714285714285714


* A more complex example: lets compute 1000 digits of the $\pi$ number using the [Bailey–Borwein–Plouffe formula](https://en.wikipedia.org/wiki/Bailey%E2%80%93Borwein%E2%80%93Plouffe_formula):

$$
\pi = \sum_{k = 0}^{\infty}\Bigg[ \frac{1}{16^k} \left( \frac{4}{8k + 1} - \frac{2}{8k + 4} - \frac{1}{8k + 5} - \frac{1}{8k + 6} \right) \Bigg]
$$

In [11]:
# https://stackoverflow.com/questions/28284996/python-pi-calculation
from decimal import Decimal, getcontext
getcontext().prec=1000
my_pi= sum(1/Decimal(16)**k * 
          (Decimal(4)/(8*k+1) - 
           Decimal(2)/(8*k+4) -
           Decimal(1)/(8*k+5) -
           Decimal(1)/(8*k+6)) for k in range(1000))
'{:.1000f}'.format(my_pi)

'3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066063155881748815209209628292540917153643678925903600113305305488204665213841469519415116094330572703657595919530921861173819326117931051185480744623799627495673518857527248912279381830119491298336733624406566430860213949463952247371907021798609437027705392171762931767523846748184676694051320005681271452635608277857713427577896091736371787214684409012249534301465495853710507922796892589235420199561121290219608640344181598136297747713099605187072113499999983729780499510597317328160963185950244594553469083026425223082533446850352619311881710100031378387528865875332083814206171776691473035982534904287554687311595628638823537875937519577818577805321712268066130019278766111959092164201

You can visit [100,000 Digits of Pi](http://www.geom.uiuc.edu/~huberty/math5337/groupe/digits.html) or [One Million Digits of Pi](http://www.piday.org/million/) to check the correctness this code.

## SciPy.org's [Numpy](http://www.numpy.org/)

Numpy provides a high-performance multidimensional array object.

### Installation

```
pip install numpy
```

### Why numpy?

Good running times.

In [12]:
import numpy as np

* Lets define a list and compute the sum of its elements, timing it:

In [13]:
l = list(range(0,100000)); print(type(l), l[:10])
%timeit sum(l)

<class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1.44 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


* An now, lets create a numpy's array and time the sum of its elements:

In [14]:
a = np.arange(0, 100000); print(type(a), a[:10])
%timeit np.sum(a)

<class 'numpy.ndarray'> [0 1 2 3 4 5 6 7 8 9]
84.9 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


* And what about a *pure* C implementation of an equivalent computation: 

In [15]:
!cat sum_array.c
!gcc -O3 sum_array.c -o sum_array
%timeit !./sum_array

#include <stdio.h>
#include <time.h>
#include "sum_array_lib.c"

#define N 100000

int main() {
  double a[N];
  int i;
  clock_t start, end;
  double cpu_time;
  for(i=0; i<N; i++) {
    a[i] = i;
  }
  start = clock();
  double sum = sum_array(a,N);
  end = clock();
  printf("%f ", sum);
  cpu_time = ((double) (end - start)) / CLOCKS_PER_SEC;
  cpu_time *= 1000000;
  printf("%f usegs\n", cpu_time);
}
4999950000.000000 166.000000 usegs
4999950000.000000 150.000000 usegs
4999950000.000000 151.000000 usegs
4999950000.000000 265.000000 usegs
4999950000.000000 152.000000 usegs
4999950000.000000 184.000000 usegs
4999950000.000000 150.000000 usegs
4999950000.000000 150.000000 usegs
4999950000.000000 151.000000 usegs
4999950000.000000 152.000000 usegs
4999950000.000000 151.000000 usegs
4999950000.000000 151.000000 usegs
4999950000.000000 151.000000 usegs
4999950000.000000 152.000000 usegs
4999950000.000000 151.000000 usegs
4999950000.000000 150.000000 usegs
4999950000.000000 151.000000 usegs

* Another example:

In [16]:
# Example extracted from https://github.com/pyHPC/pyhpc-tutorial
lst = range(1000000)

for i in lst[:10]:
    print(i, end=' ')
print()

%timeit [i + 1 for i in lst] # A Python list comprehension (iteration happens in C but with PyObjects)
x = [i + 1 for i in lst]

print(x[:10])

arr = np.arange(1000000) # A NumPy list of integers
%timeit arr + 1 # Use operator overloading for nice syntax, now iteration is in C with ints
y = arr + 1

print(y[:10])

0 1 2 3 4 5 6 7 8 9 
196 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
2.64 ms ± 57.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
[ 1  2  3  4  5  6  7  8  9 10]


* Looking for information of numpy's *something*:

In [17]:
np.lookfor('invert')

Search results for 'invert'
---------------------------
numpy.bitwise_not
    Compute bit-wise inversion, or bit-wise NOT, element-wise.
numpy.matrix.getI
    Returns the (multiplicative) inverse of invertible `self`.
numpy.in1d
    Test whether each element of a 1-D array is also present in a second array.
numpy.isin
    Calculates `element in test_elements`, broadcasting over `element` only.
numpy.transpose
    Permute the dimensions of an array.
numpy.linalg.inv
    Compute the (multiplicative) inverse of a matrix.
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.random.SFC64
    BitGenerator for Chris Doty-Humphrey's Small Fast Chaotic PRNG.
numpy.linalg.tensorinv
    Compute the 'inverse' of an N-dimensional array.
numpy.linalg.matrix_power
    Raise a square matrix to the (integer) power `n`.

* Remember that it's possible to use the tabulator to extend some command or to use a wildcard in Ipython to get the numpy's stuff:

In [18]:
np.*?

### Creating (simple) [arrays](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html) in Numpy
A simple array is a grid of values, all of the same type, indexed by a tuple of nonnegative integers.

### 1D arrays

* Creating an empty array:

In [19]:
a = np.array([], dtype=np.uint8)
a

array([], dtype=uint8)

* Creating an array using a list:

In [20]:
a = np.array([1, 2, 3])
print(type([1, 2, 3]))
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


* Getting the number of dimensions of an array:

In [21]:
print(a.ndim)

1


* Printing an array:

In [22]:
print(a)

[1 2 3]


* Printing the *shape* (which always is a tuple) of an array:

In [23]:
print(a.shape)

(3,)


* Native Python's [`len()`](https://docs.python.org/3.6/library/functions.html#len) also works:

In [24]:
print(len(a))

3


* A more exotic definition using [`linspace()`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linspace.html):

In [25]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

* Arrays can be created from different types of contaniers (which store complex numbers in this case):

In [32]:
c = [[1,1.0],(1+1j,.3)]
print(type(c), type(c[0]), type(c[1]))
x = np.array(c)
x

<class 'list'> <class 'list'> <class 'tuple'>


array([[1. +0.j, 1. +0.j],
       [1. +1.j, 0.3+0.j]])

* Accessing to an element:

In [33]:
print(a, a[0], a[1])

[1 2 3] 1 2


In [34]:
a[0] = 0
print(a)

[0 2 3]


* Appending elements:

In [35]:
a = np.append(a, 4)
a

array([0, 2, 3, 4])

### 1.3.3. 2D arrays

* Creating a 2D array with two 1D arrays:

In [36]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b[1, 1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


* With zeroes:

In [37]:
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


* The default dtype is `float64`:

In [38]:
print(type(a[0][0]))

<class 'numpy.float64'>


* With ones:

In [39]:
a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


* With an arbitrary scalar:

In [40]:
a = np.full((5,5), 2)
print(a)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


* The identity matrix:

In [41]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


* With random data:

In [42]:
a = np.random.random((5,5))
print(a)

[[0.76359604 0.37438693 0.9668897  0.21191937 0.57088537]
 [0.39113527 0.61198963 0.82669883 0.58168569 0.00714437]
 [0.11876243 0.28247245 0.25086161 0.43024645 0.32745178]
 [0.23669245 0.72280935 0.38548107 0.76023302 0.23836566]
 [0.81979262 0.61351946 0.41045962 0.0651604  0.6361771 ]]


In [43]:
a = np.random.random((5,5))
print(a)

[[0.66206955 0.20171114 0.40630419 0.43529802 0.48162876]
 [0.63070354 0.3021124  0.77625059 0.32604168 0.67310305]
 [0.25258922 0.5058811  0.34380791 0.10797026 0.11196849]
 [0.98097959 0.34919788 0.29218995 0.85820573 0.54333858]
 [0.17121655 0.27729179 0.9991036  0.33722011 0.99512996]]


* Filled with [arbitrary](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.empty_like.html) data and with a previously defined shape:

In [44]:
b = np.empty_like(a)
print(b)

[[0.66206955 0.20171114 0.40630419 0.43529802 0.48162876]
 [0.63070354 0.3021124  0.77625059 0.32604168 0.67310305]
 [0.25258922 0.5058811  0.34380791 0.10797026 0.11196849]
 [0.98097959 0.34919788 0.29218995 0.85820573 0.54333858]
 [0.17121655 0.27729179 0.9991036  0.33722011 0.99512996]]


* With a 1D list comprehension:

In [45]:
a = np.array([i for i in range(5)])
print(a, a[1], a.shape)

[0 1 2 3 4] 1 (5,)


* With a 2D list comprehension:

In [46]:
a = np.array([[j+i*5 for j in range(10)] for i in range(5)])
print(a, a.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]] (5, 10)


* Accessing to a row of a matrix:

In [47]:
a[1] # Get row 2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* Accessing to an element of a matrix:

In [48]:
a[1][2] # Get column 3 of row 2

7

In [49]:
a[1,2] # Get element of coordinates (1,2)

7

* Getting elements of a matrix using "integer array indexing":

In [50]:
print(a)
print(a[[0, 1, 2], [3, 2, 1]])

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]
[ 3  7 11]


* The same integer array indexing using comprehension lists:

In [51]:
print(a[np.array([i for i in range(3)]), np.array([i for i in range(3,0,-1)])])

[ 3  7 11]


* The same using [`np.arange()`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.arange.html):

In [52]:
print(np.arange(3))
print(np.arange(3,0,-1))
print(a[np.arange(3), np.arange(3,0,-1)])

[0 1 2]
[3 2 1]
[ 3  7 11]


### 1.3.4. N-dimensional array

In [53]:
a = np.ndarray((2,3,4,2))
a

array([[[[ 2.68156159e+154, -4.33073861e-311],
         [ 2.25073505e-314,  2.36630943e-314],
         [ 2.36616555e-314,  2.36616552e-314],
         [ 2.25383969e-314,  2.36630952e-314]],

        [[ 2.25729742e-314,  2.25729783e-314],
         [ 2.25101095e-314,  2.36630962e-314],
         [ 2.25730384e-314,  2.36616590e-314],
         [ 2.25081006e-314,  2.36630974e-314]],

        [[ 2.25035057e-314,  2.25074477e-314],
         [ 2.36629934e-314,  2.25069889e-314],
         [ 2.25178858e-314,  2.36630981e-314],
         [ 2.25078711e-314,  2.27778440e-314]]],


       [[[ 2.36617662e-314,  2.25730697e-314],
         [ 2.25322667e-314,  2.27654410e-314],
         [ 2.36151565e-314,  2.26494379e-314],
         [ 2.26080363e-314,  2.36605115e-314]],

        [[ 2.25180262e-314,  2.36630987e-314],
         [ 2.27778444e-314,  2.36617672e-314],
         [ 2.36630993e-314,  2.27669613e-314],
         [ 2.36631003e-314,  2.36631012e-314]],

        [[ 2.25382717e-314,  2.36617839e-314],
 

In [54]:
a.shape

(2, 3, 4, 2)

In [55]:
# The same can be done with:
a = np.ndarray(2*3*4*2).reshape(2, 3, 4, 2)
a.shape

(2, 3, 4, 2)

### 1.4. Slicing

In [56]:
a = np.array([[j+i*5 for j in range(10)] for i in range(5)])
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

* Get all rows of a matrix (the whole matrix):

In [57]:
a[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [58]:
print(a)
a[::] # Notation: [starting index : stoping index : step]
# By default, start = 0, stop = maximum, step = 1

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
print(a)
a[0:]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
print(a)
a[0::]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [61]:
a[:a.shape[1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [62]:
a[:a.shape[1]:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

* Get all rows of a matrix, except the first one:

In [63]:
print(a)
a[1:]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [64]:
print(a)
a[1::]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

* Get the first two rows of a matrix:

In [65]:
print(a)
a[0:2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

* Get the even rows of a matrix:

In [66]:
print(a)
a[0::2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

* Get the odd columns of a matrix:

In [67]:
print(a)
a[:,1::2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14],
       [11, 13, 15, 17, 19],
       [16, 18, 20, 22, 24],
       [21, 23, 25, 27, 29]])

* Get the odd rows of a matrix:

In [68]:
print(a)
a[:][1::2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
a[1::2]

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

* Getting the second row:

In [70]:
print(a)
a[1,:]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* Getting the third column:

In [71]:
print(a)
a[:,2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([ 2,  7, 12, 17, 22])

* Getting a top-left $2\times 2$ submatrix:

In [72]:
print(a)
a[:2,:2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[0, 1],
       [5, 6]])

* Getting a bottom-right $2\times 2$ submatrix:

In [73]:
print(a)
a[a.shape[0]-2:,a.shape[1]-2:]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[23, 24],
       [28, 29]])

In [74]:
a[a.shape[0]-2::,a.shape[1]-2::]

array([[23, 24],
       [28, 29]])

* Sampling in horizontal every 2 elements, starting at row 2:

In [75]:
print(a)
a[:,1::2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 5  6  7  8  9 10 11 12 13 14]
 [10 11 12 13 14 15 16 17 18 19]
 [15 16 17 18 19 20 21 22 23 24]
 [20 21 22 23 24 25 26 27 28 29]]


array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14],
       [11, 13, 15, 17, 19],
       [16, 18, 20, 22, 24],
       [21, 23, 25, 27, 29]])

 ### 1.5. Boolean array indexing

* Finding the elements bigger than ...

In [76]:
bool_idx = (a>12)
print(bool_idx)

[[False False False False False False False False False False]
 [False False False False False False False False  True  True]
 [False False False  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


* Printing the elements bigger than ...

In [77]:
print(a[bool_idx])

[13 14 13 14 15 16 17 18 19 15 16 17 18 19 20 21 22 23 24 20 21 22 23 24
 25 26 27 28 29]


### 1.6. Elementwise (vectorial-vectorial and vectorial-scalar) math

* Create an zero-ed matrix:

In [78]:
a = np.zeros((5,5), np.int32)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* Change to 1 from coordinate (1,1) to coordinate (4,4):

In [79]:
a[1:4,1:4] = 1
print(a)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


* Vectorial-scalar addition:

In [80]:
a[1:4, 1:4] += 1
print(a)

[[0 0 0 0 0]
 [0 2 2 2 0]
 [0 2 2 2 0]
 [0 2 2 2 0]
 [0 0 0 0 0]]


* A new matrix:

In [81]:
b = np.ones((5,5), np.int32)
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


* Vectorial addition:

In [82]:
c = a + b
print(c)

[[1 1 1 1 1]
 [1 3 3 3 1]
 [1 3 3 3 1]
 [1 3 3 3 1]
 [1 1 1 1 1]]


* Vectorial substraction:

In [83]:
d = c - b
print(d)

[[0 0 0 0 0]
 [0 2 2 2 0]
 [0 2 2 2 0]
 [0 2 2 2 0]
 [0 0 0 0 0]]


* Vectorial multiplication (not matrix multiplication!):

In [84]:
c = c * d
print(c)

[[0 0 0 0 0]
 [0 6 6 6 0]
 [0 6 6 6 0]
 [0 6 6 6 0]
 [0 0 0 0 0]]


* Floating-point vectorial division:

In [85]:
c = c / b
print(c)

[[0. 0. 0. 0. 0.]
 [0. 6. 6. 6. 0.]
 [0. 6. 6. 6. 0.]
 [0. 6. 6. 6. 0.]
 [0. 0. 0. 0. 0.]]


* Fixed-point (integer) vectorial division:

In [86]:
c = d // b
print(c)

[[0 0 0 0 0]
 [0 2 2 2 0]
 [0 2 2 2 0]
 [0 2 2 2 0]
 [0 0 0 0 0]]


### 1.7. Broadcasting
In vectorized operations, NumPy "extends" scalars and arrays with one of its dimensions equal to 1 to the size of the other(s) array(s).

In [87]:
a = np.ones((5,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [88]:
b = np.arange(1)
b

array([0])

In [89]:
b += 1
b

array([1])

* Broadcasting of a $1\times 1$ matrix:

In [90]:
a+b # 'a' is 5x3 and 'b' is 1x1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

* Broadcasting of a $1\times 3$ matrix:

In [91]:
b = np.arange(3)
b

array([0, 1, 2])

In [92]:
a+b # 'a' is 5x3 and 'b' is '1x3'

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

* Broadcasting of a $5\times 1$ matrix:

In [93]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [94]:
b = b.reshape((5,1)) # (Rows, Columns)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [95]:
a+b

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])

* If the arrays have different shapes and s can not be "broadcasted", `ValueError: frames are not aligned` is thrown.

In [96]:
b = np.arange(4)[:, None]
b

array([[0],
       [1],
       [2],
       [3]])

In [97]:
a.shape

(5, 3)

In [98]:
b.shape

(4, 1)

In [99]:
a+b

ValueError: operands could not be broadcast together with shapes (5,3) (4,1) 

### 1.8. Matricial math
Provides basic matrix computation.

* Let's define a "chessboard" matrix:

In [ ]:
a = np.array([[(i+j)%2 for j in range(10)] for i in range(10)])
print(a, a.shape)

... and a 1-column matrix:

In [ ]:
b = np.array([[1] for i in range(10)])
print(b, b.shape)

* Product matrix-matrix:

In [ ]:
c = np.dot(a,b)
print(c)

* Sum of all elements of a matrix:

In [ ]:
print(np.sum(c))

In [ ]:
print(np.sum(a))

* Compute the maximum of a matrix:

In [ ]:
print(np.max(c))

* Matrix transpose:

In [ ]:
print(c.T, c.T.shape, c.shape)

### 1.9. How fast is Numpy's array math?

In [ ]:
a = np.array([[(i*10+j) for j in range(10)] for i in range(10)])
print(a, a.shape)

In [ ]:
a[:1] # First row (a matrix)

In [ ]:
a[:1].shape

In [ ]:
a[:1][0] # First element of a matrix of one elment (a vector)

In [ ]:
a[:1][0].shape

In [ ]:
b = a[:1][0]
b

* Add `b[]` to all the rows of `a[][]` using scalar arithmetic:

In [ ]:
c = np.empty_like(a)
def add():
    for i in range(a.shape[1]):
        for j in range(a.shape[0]):
            c[i, j] = a[i, j] + b[j]
%timeit add()
print(c)

* Add `b[]` to all the rows of `a[][]` using vectorial arithmetic:

In [ ]:
c = np.empty_like(a)
def add():
    for i in range(a.shape[1]):
        c[i, :] = a[i, :] + b
%timeit add()
print(c)

* Add `b[]` to all the rows of `a[][]` using fully vectorial arithmetic:

In [ ]:
%timeit c = a + b # <- broadcasting is faster
print(c)

### 1.10. Structured arrays

* Create a 1D array of (two) records, where each record has the structure (int, float, char[10]).

In [ ]:
x = np.array([(1,2.,'Hello'), (3,4.,"World")],
             dtype=[('first', 'i4'),('second', 'f4'), ('third', 'S10')])
x

* Get the first element of every record:

In [ ]:
x['first']

* Get the first record:

In [ ]:
x[0]

* Get the second element of every record:

In [ ]:
x['second']

* Third element of every record:

In [ ]:
x['third']

### Output data to an ASCII file

In [26]:
data = np.array([[1., 200.], [2., 150.], [3., 250.]])
np.savetxt('data.txt', data)
!cat data.txt

1.000000000000000000e+00 2.000000000000000000e+02
2.000000000000000000e+00 1.500000000000000000e+02
3.000000000000000000e+00 2.500000000000000000e+02


* Input data from an ASCII file:

In [27]:
np.genfromtxt('data.txt')

array([[  1., 200.],
       [  2., 150.],
       [  3., 250.]])

* Output data to a binary file:

In [28]:
ofile = open("data.float64", mode='wb')
data.tofile(ofile)

* Input data from a binary file:

In [29]:
np.fromfile('data.float64', dtype=np.float64)

array([  1., 200.,   2., 150.,   3., 250.])

* Create a binary file using C:

In [30]:
!cat create_float64.c
!gcc create_float64.c -o create_float64
!./create_float64

#include <stdio.h>

#define N 10

int main() {
  double a[N];
  int i;
  FILE *ofile = fopen("data.float64", "wb");
  for(i=0; i<N; i++) {
    a[i] = i;
  }
  fwrite(a, sizeof(double), N, ofile);
  fclose(ofile);
  fprintf(stderr,"create_float64: done\n");
}
create_float64: done


* Input data from the file created in C:

In [31]:
np.fromfile('data.float64', dtype=np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 2. [Matplotlib](http://matplotlib.org)
A Python 2D plotting library.

### 2.1. Installation

```
pip install matplotlib
```

### 2.2. Configure Matplotlib in-line of IPython (~Jupyter) notebook

In [ ]:
%matplotlib inline

### 2.3. Importing it

In [ ]:
import matplotlib.pyplot as plt

### 2.4. Drawing data structures (matrices):

In [ ]:
chess_board = np.zeros([8, 8], dtype=int)
chess_board[0::2, 1::2] = 1
chess_board[1::2, 0::2] = 1
plt.matshow(chess_board, cmap=plt.cm.gray)

### 2.5. Drawing 2D curves

In [ ]:
resolution = 100
x = np.arange(0, 3*np.pi, np.pi/resolution)
si = np.sin(x)
co = np.cos(x)
plt.plot(x, si, c = 'r')
plt.plot(x, co, c = 'g')
plt.legend(['$\sin(x)$', '$\cos(x)$'])
plt.xlabel('radians')
plt.title('sine($x$) vs. cosine($x$)')
plt.xticks(x*resolution, ['0', '$\pi$', '$2\pi$'], rotation='horizontal')
plt.xlim(0,3*np.pi)
plt.show()

### 2.6. Drawing 3D curves

In [ ]:
x = np.array([[(x+y)/25 for x in range(256)] for y in range(256)])
si = np.sin(x)
plt.imshow(si, cmap='hot', interpolation='nearest')
plt.show()

In [ ]:
# https://github.com/AeroPython/Taller-Aeropython-PyConEs16
def funcion(x,y):
    return np.cos(x) + np.sin(y)

x_1d = np.linspace(0, 5, 100)
y_1d = np.linspace(-2, 4, 100)
X, Y = np.meshgrid(x_1d, y_1d)
Z = funcion(X,Y)
plt.contourf(X, Y, Z, np.linspace(-2, 2, 100),cmap=plt.cm.Spectral)
plt.colorbar()
cs = plt.contour(X, Y, Z, np.linspace(-2, 2, 9), colors='k')
plt.clabel(cs)

## 3. [SciPy](https://docs.scipy.org/doc/scipy/reference/)
[SciPy](http://cs231n.github.io/python-numpy-tutorial/#numpy-array-indexing) provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications such as:
1. [Custering](https://docs.scipy.org/doc/scipy/reference/cluster.html).
2. [Discrete Fourier Analysis](https://docs.scipy.org/doc/scipy/reference/fftpack.html).
3. [Interpolation](https://docs.scipy.org/doc/scipy/reference/interpolate.html).
4. [Linear algebra](https://docs.scipy.org/doc/scipy/reference/linalg.html).
5. [Signal](https://docs.scipy.org/doc/scipy/reference/signal.html) and [Image processing](https://docs.scipy.org/doc/scipy/reference/ndimage.html).
6. [Optimization](https://docs.scipy.org/doc/scipy/reference/optimize.html).
7. [Sparse matrix](https://docs.scipy.org/doc/scipy/reference/sparse.html) and [sparse linear algebra](https://docs.scipy.org/doc/scipy/reference/sparse.linalg.html).



### 3.1. Installation

```
pip install scipy
```

### 3.1.1. Optimization example

In [ ]:
# http://www.scipy-lectures.org/advanced/mathematical_optimization/
from scipy import optimize

In [ ]:
def f(x):
    return -np.exp(-(x - .7)**2)

In [ ]:
sol = optimize.brent(f)
print('min =', sol, '\nx =', f(sol))

In [ ]:
x = np.arange(-10, 10, 0.1)
plt.plot(x, f(x))
plt.plot([sol],[f(sol)], 'ro')
plt.show()

## 4. [Pandas](http://pandas.pydata.org/)
High-performance data structures and data analysis tools for the Python programming language (similar to [R](https://en.wikipedia.org/wiki/R_(programming_language)). Some tools are:
1. [Statistical functions (covariance, correlation)](http://pandas.pydata.org/pandas-docs/stable/computation.html#statistical-functions).
2. [Window functions](http://pandas.pydata.org/pandas-docs/stable/computation.html#window-functions).
3. [Time series](http://pandas.pydata.org/pandas-docs/stable/timeseries.html).
4. [Analysis of sparse data](http://pandas.pydata.org/pandas-docs/stable/sparse.html).

### 4.1. Installation

```
pip3 install pandas
```

### 4.2. Example

Create a table with data:

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'int_col' : [1, 2, 6, 8, -1],
                    'float_col' : [0.1, 0.2, 0.2, 10.1, None],
                    'str_col' : ['a', 'b', None, 'c', 'a']})
print(df)
df

Arithmetic average of a column:

In [ ]:
df2 = df.copy()
mean = df2['float_col'].mean()
mean

Replace undefined elements:

In [ ]:
df3 = df['float_col'].fillna(mean)
df3

Create a table by means of columns:

In [ ]:
df4 = pd.concat([df3, df['int_col'], df['str_col']], axis=1)
df4

## 5. [SymPy](http://www.sympy.org/en/index.html)
A Python library for symbolic mathematics. Among others things, it provides:
1. [Symbolic simplification](http://docs.sympy.org/latest/tutorial/simplification.html).
2. [Calculus (derivatives, integrals, limits, and series expansions)](http://docs.sympy.org/latest/tutorial/calculus.html).
3. [Algebraic solver](http://docs.sympy.org/latest/tutorial/solvers.html).
4. [Matrix operations](http://docs.sympy.org/latest/tutorial/matrices.html).
5. [Combinatorics](http://docs.sympy.org/latest/modules/combinatorics/index.html)
6. [Cryptography](http://docs.sympy.org/latest/modules/crypto.html).

### 5.1. Install
```
pip install sympy
```

### 5.2. Example

In [ ]:
from sympy import init_session
init_session(use_latex='matplotlib')

In [ ]:
# https://github.com/AeroPython/Taller-Aeropython-PyConEs16
expr = cos(x)**2 + sin(x)**2
expr

In [ ]:
simplify(expr)

In [ ]:
expr.subs(x, y**2)

In [ ]:
expr = (x + y) ** 2
expr

In [ ]:
expr = expr.expand()
expr

In [ ]:
expr = expr.factor()
expr

In [ ]:
expr = expr.integrate(x)
expr

In [ ]:
expr = expr.diff(x)
expr