# TensorFlow Core

TensorFlow is basically a software library (developed by Google) for numerical computation using data flow graphs where:

    nodes in the graph represent mathematical operations.
    edges in the graph represent the multidimensional data arrays (called tensors) communicated between them.

TensorFlow Core refers to the foundational, open-source machine learning library developed by the TensorFlow team at Google.

## Computational Graphs

Any TensorFlow Core program can be divided into two discrete sections:

1. Building the computational graph. A computational graph is nothing but a series of TensorFlow operations arranged into a graph of nodes. Each node takes zero or more tensors as inputs and produces a tensor as an output.
2. Running the computational graph. To actually evaluate the nodes, we must run the computational graph within a session. A session encapsulates the control and state of the TensorFlow runtime.

![](graph1.png)
Here, add is a node which represents addition operation. a and b are input tensors and c is the resultant tensor. This flexible architecture allows you to deploy computation to one or more CPUs or GPUs in a desktop, server, or mobile device with a single API!

In [1]:
import tensorflow as tf

2024-01-17 06:47:48.324373: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-17 06:47:48.469263: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-17 06:47:48.469338: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-17 06:47:48.485831: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-17 06:47:48.529804: I tensorflow/core/platform/cpu_feature_guar

In [5]:
node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)
print("Sum of node1 and node2 is:", node3.numpy())

Sum of node1 and node2 is: 8


## Variables

 Variables are in-memory buffers containing tensors. They must be explicitly initialized and can be saved to disk.

In [7]:
node = tf.Variable(tf.zeros([2, 2]))
print("Tensor value before addition:\n", node.numpy())
node.assign(node + tf.ones([2, 2]))  # Elementwise addition to the tensor
print("Tensor value after addition:\n", node.numpy())

Tensor value before addition:
 [[0. 0.]
 [0. 0.]]
Tensor value after addition:
 [[1. 1.]
 [1. 1.]]


## Functions

In [11]:
# Create two matrices
matrix_a = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
matrix_b = tf.constant([[7, 8], [9, 10], [11, 12]], dtype=tf.int32)

# Define a function for matrix multiplication
@tf.function
def matrix_multiply(a, b):
    return tf.matmul(a, b)

# Use the function to multiply the matrices
result = matrix_multiply(matrix_a, matrix_b)

# Print the result
print("Result of matrix multiplication:\n", result.numpy())


Result of matrix multiplication:
 [[ 58  64]
 [139 154]]
